Project/BeCute/urls.py
from django.contrib import admin
from django.urls import path, include

from BeCute.views import logout_view, index_view, error_view
from django.contrib.auth.decorators import login_required
from haystack.views import basic_search
from . import views

urlpatterns = [
    path('', index_view, name='index'),
    path("admin/", admin.site.urls),
    path("customers/", include("customer.urls")),
    path("barbers/", include("barber.urls")),
    path("accounts/", include("account.urls")),
    path(r'logout/', logout_view, name='logout'),
    path(r'search/', login_required(basic_search), name='basic_search'),
    path("error/", error_view, name="error")
]

Project/barber/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    path("", login_required(views.main), name="main"),
    path(
        "profile/",
        login_required(views.BarberProfileView.as_view()),
        name="barber-profile",
    ),
    path("schedule/", login_required(views.schedule), name="schedule"),
    path(
        "cancel-schedule/<int:schedule_id>/",
        login_required(views.cancel_schedule),
        name="cancel-schedule",
    ),
    path('<str:barbershop_id>/profile',
         views.profile,
         name='barber_info'),
    path('add-service/', login_required(views.add_service), name='add_service'),
    path('edit-serivce/', login_required(views.edit_service), name='edit_service'),
]

Project/barber/models.py
from django.db import models
from django.urls import reverse

from account.models import CustomUser


# from django.contrib.gis.db import models as spatial_models


class Service(models.Model):
    name = models.CharField(max_length=50)
    duration = models.DurationField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discounted_price = models.DecimalField(max_digits=6, decimal_places=2, default=0.0)


class BarberShop(models.Model):
    name = models.CharField(max_length=50)
    barber = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=123456)
    introduction = models.CharField(max_length=1000, default="")
    service = models.ManyToManyField(
        Service, through="BarberService", through_fields=("shop", "service")
    )
    address = models.CharField(max_length=200, default="")
    city = models.CharField(max_length=50, default="")
    foundation_year = models.CharField(max_length=4, default="2019")
    phone = models.CharField(max_length=20, default="")

    # location = spatial_models.PointField()

    def get_absolute_url(self):
        return reverse('barber_info', kwargs={'barbershop_id': self.name})


class BarberService(models.Model):
    shop = models.ForeignKey(BarberShop, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)


class Schedule(models.Model):
    shop = models.ForeignKey(BarberShop, on_delete=models.CASCADE)
    start = models.DateTimeField()
    duration = models.DurationField()

Project/barber/forms.py
from django import forms


class BarberShopSearchForm(forms.Form):
    search_text = forms.CharField(
        required=True,
        label='Search name',
        widget=forms.TextInput(attrs={'placeholder': 'search here!'})
    )


class AddServiceToBarbershop(forms.Form):
    service_name = forms.CharField(max_length=50, required=True)
    price = forms.DecimalField(required=True)
    duration = forms.DurationField(required=True)
    discounted_price = forms.DecimalField(required=False)

Project/barber/views.py
import datetime

from django.db.models import Q, F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic

from BeCute.misc import parse_datetime
from account.models import CustomUser
from barber.models import Schedule, BarberShop, Service, BarberService
from customer.models import Reservation, Comment
from barber.forms import AddServiceToBarbershop


def main(request):
    request.session['user_type'] = 'barber'
    request.session['page'] = 'main'
    return render(request, "barber/index.html", context={})


class NameAndNumber():
    def __init__(self, name, number, number2, object):
        self.name = name
        self.number = number
        self.number2 = number2
        self.object = object


class BarberProfileView(generic.TemplateView):
    template_name = "barber/profile.html"

    def get_context_data(self, **kwargs):
        self.request.session['user_type'] = 'barber'
        self.request.session['page'] = 'profile'
        context = super(BarberProfileView, self).get_context_data(**kwargs)
        user = self.request.user
        shop = BarberShop.objects.get(
            barber=user
        )

        shop_reservations = Reservation.objects.filter(shop=shop)
        upcoming_reservations = shop_reservations.filter(
            state=Reservation.STATE_RESERVED,
            start__gte=datetime.datetime.now()
        ).order_by("start")[:5]
        previous_reservations = shop_reservations.filter(
            start__lt=datetime.datetime.now()
        ).order_by("state", "-start")

        shop_schedules = Schedule.objects.filter(
            shop=shop,
            start__gte=datetime.datetime.now()
        )[:5]

        barber_name = BarberShop.objects.get(barber=user).name
        previous_reservations_list = list(previous_reservations)

        loving_customers = {}
        customers = {}
        for reservation in previous_reservations_list:
            if reservation.customer.username in loving_customers.keys():
                loving_customers[reservation.customer.username] += 1
            else:
                loving_customers[reservation.customer.username] = 1
                customers[reservation.customer.username] = reservation.customer
        loving_customers_list_of_values = list(loving_customers.values())
        loving_customers_list_of_values = sorted(loving_customers_list_of_values, reverse=True)

        upcoming_reservations_list = list(upcoming_reservations)
        loving_customers_upcoming = {}
        for reservation in upcoming_reservations_list:
            if reservation.customer.username in loving_customers_upcoming.keys():
                loving_customers_upcoming[reservation.customer.username] += 1
            else:
                loving_customers_upcoming[reservation.customer.username] = 1

        top_customer = []
        for key in loving_customers.keys():
            if len(loving_customers_list_of_values) > 0 and loving_customers[key] == loving_customers_list_of_values[0]:
                if key in loving_customers_upcoming.keys():
                    top_customer.append(NameAndNumber(key, loving_customers[key], loving_customers_upcoming[key], customers[key]))
                else:
                    top_customer.append(NameAndNumber(key, loving_customers[key], 0, customers[key]))

        for key in loving_customers.keys():
            if len(loving_customers_list_of_values) > 1 and loving_customers[key] == loving_customers_list_of_values[1]:
                if key in loving_customers_upcoming.keys():
                    top_customer.append(
                        NameAndNumber(key, loving_customers[key], loving_customers_upcoming[key], customers[key]))
                else:
                    top_customer.append(NameAndNumber(key, loving_customers[key], 0, customers[key]))
        for key in loving_customers.keys():
            if len(loving_customers_list_of_values) > 2 and loving_customers[key] == loving_customers_list_of_values[2]:
                if key in loving_customers_upcoming.keys():
                    top_customer.append(NameAndNumber(key, loving_customers[key], loving_customers_upcoming[key], customers[key]))
                else:
                    top_customer.append(NameAndNumber(key, loving_customers[key], 0, customers[key]))

        top_customer = top_customer[0: min(3, len(top_customer))]

        context.update(
            upcoming_reservations=upcoming_reservations,
            previous_reservations=previous_reservations,
            shop_schedules=shop_schedules,
            barber_name=barber_name,
            top_customer=top_customer,
        )
        return context


def schedule(request):
    request.session['user_type'] = 'barber'
    request.session['page'] = 'schedule'

    try:
        shop = BarberShop.objects.get(barber=request.user)
    except BarberShop.DoesNotExist:
        # return HttpResponse("bad request.")
        request.session['user_type'] = 'barber'
        request.session['error_message'] = 'Bad Request!'
        return redirect("/error/")
    if request.method == "POST":
        start_dt = parse_datetime(request.POST.get("start", ""))
        try:
            duration = datetime.timedelta(minutes=int(request.POST.get("duration")))
        except (TypeError, ValueError):
            duration = None
        if not start_dt and duration:
            # return HttpResponse("bad request")
            request.session['user_type'] = 'barber'
            request.session['error_message'] = 'Bad Request!'
            return redirect("/error/")
        if Schedule.objects.filter(
            Q(start__lte=start_dt, start__gt=start_dt - F("duration"))
            | Q(start__lt=start_dt + duration, start__gte=start_dt - F("duration"))
            | Q(start__gte=start_dt, start__lte=start_dt + duration - F("duration")),
            shop=shop,
        ).exists():
            # return HttpResponse("there is an overlap with other free times")
            request.session['user_type'] = 'barber'
            request.session['error_message'] = 'There is an overlap with other free times!'
            return redirect("/error/")

        Schedule.objects.create(shop=shop, start=start_dt, duration=duration)

        return redirect("/barbers/profile/")

    else:
        return render(request, "barber/new_schedule.html")


def cancel_schedule(request, schedule_id):
    request.session['user_type'] = 'barber'
    request.session['page'] = 'cancel_schedule'
    schedule_to_be_deleted = Schedule.objects.filter(
        id=schedule_id, shop__barber=request.user
    ).first()
    if schedule_to_be_deleted:
        if Reservation.objects.filter(
            shop=schedule_to_be_deleted.shop,
            start__gt=schedule_to_be_deleted.start,
            start__lt=schedule_to_be_deleted.start + schedule_to_be_deleted.duration,
            state=Reservation.STATE_RESERVED,
        ).exists():
            # return HttpResponse("There are reservations in this time.")
            request.session['user_type'] = 'barber'
            request.session['error_message'] = "There are reservations in this time."
            return redirect("/error/")
        schedule_to_be_deleted.delete()
    return redirect("/barbers/profile")


def profile(request, barbershop_id):
    # if not 'user_type' in request.session:
    # if request.session['user_type'] == 'barber':
    #     request.session['user_type'] = 'barber'
    request.session['page'] = 'profile_visit'
    barbershop = BarberShop.objects.get(
        name=barbershop_id
    )

    comments = Comment.objects.filter(barbershop=barbershop)
    user = request.user
    show_comment_form = False
    if user.type == CustomUser.USER_TYPE_CLIENT:
        show_comment_form = True
    services = barbershop.service.all()
    my_comments_list = list(Comment.objects.filter(barbershop=barbershop))
    rating = 0
    for comment in my_comments_list:
        rating += comment.rate
    if len(my_comments_list) != 0:
        rating /= len(my_comments_list)
    else:
        rating = 0
    barbershops = list(BarberShop.objects.all())
    rank = 1
    for barber_shop in barbershops:
        if barber_shop == barbershop:
            continue
        my_comments_list = list(Comment.objects.filter(barbershop=barber_shop))
        rating_barber_shop = 0
        for comment in my_comments_list:
            rating_barber_shop += comment.rate
        if len(my_comments_list) != 0:
            rating_barber_shop /= len(my_comments_list)
        else:
            rating_barber_shop = 0
        if rating < rating_barber_shop:
            rank += 1
    total = len(barbershops)

    return render(request, 'barber/info.html', {'barbershop': barbershop, 'shop_comments': comments, 'add_comment': show_comment_form, 'services': services, "rating": round(rating), "rating_exact": rating, "rank": rank, "total_number_of_barbershops": total})


def add_service(request):
    request.session['user_type'] = 'barber'
    request.session['page'] = 'add_service'
    try:
        shop = BarberShop.objects.get(barber=request.user)
    except BarberShop.DoesNotExist:
        # return HttpResponse("bad request.")
        request.session['user_type'] = 'barber'
        request.session['error_message'] = 'Bad Request!'
        return redirect("/error/")
    if request.method == "POST":
        price = request.POST.get("price")
        try:
            price_float = float(price)
            if price_float < 0:
                raise TypeError
        except:
            # return HttpResponse("The price should be valid.")
            # return HttpResponse("bad request.")
            request.session['user_type'] = 'barber'
            request.session['error_message'] = 'The price should be valid!'
            return redirect("/error/")

        try:
            discounted_price = float(request.POST.get("discounted_price"))

Project/barber/templates/barber/edit_service.html
{% extends 'base/base_form.html' %}
{% load static %}
{% block title %}New Service{% endblock %}
{% block form %}
    <div class="col-md-12">
        <form id="service_form" class="form-horizontal" method="POST" action="{% url 'edit_service' %}">
            {% csrf_token %}
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_service_name">Service Name</label>
                    <select id="id_service_name" name="service_name" class="form-control">
                        {% for service in services%}
                            <option selected value="{{ service.name }}">{{ service.name }}</option>
                        {% endfor %}
                    </select>
                    <div class="text-danger">
                        {{ form.service_name.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_service_new_name">Service New Name</label>
                    <input type='text' id="id_service_new_name" class="form-control" name="service_new_name" />
                    <div class="text-danger">
                        {{ form.service_name.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_duration">Duration</label>
                    <div class="row">
                        <input hidden id="id_duration" name="duration">
                        <div class="col-md-5">
                            <div class='input-group'>
                                <input type='number' id="id_duration_hour" min="0" max="6" class="form-control" value="0"/>
                                <span class="input-group-addon">
                                    <span>hours</span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1">
                            <div class='input-group'>
                                <input type='number' id="id_duration_minute" min="0" max="59" class="form-control" value="30"/>
                                <span class="input-group-addon">
                                    <span>minutes</span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="text-danger">
                        {{ form.duration.errors }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_price">Price</label>
                    <input type='text' id="id_price" class="form-control" name="price"/>
                    <div class="text-danger">
                        {{ form.price.errors }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_discounted_price">Discount</label>
                    <input type='text' id="id_discounted_price" class="form-control" name="discounted_price"/>
                    <div class="text-danger">
                        {{ form.discounted_price.errors }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    <button id="id_save_button" class="btn btn-primary" type="button" onclick="cleanData()"><span class="glyphicon glyphicon-save"> edit </span></button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block sidebar_image %}{% static 'base/img/edit_service.png' %}{% endblock %}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
        function cleanTwoDigitInteger(number) {
            return Math.floor(number / 10) + '' + number % 10;
        }
        function cleanData() {
            let duration = parseInt($('#id_duration_hour').val() * 60) + parseInt($('#id_duration_minute').val());
            $('#id_duration').val(duration);
            $('#service_form').submit();
        }
    </script>
{% endblock %}

Project/barber/templates/barber/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BeCute Barber</title>
</head>
<body>
Barber landing page
</body>
</html>

Project/barber/templates/barber/new_schedule.html
{% extends 'base/base_form.html' %}
{% load static %}
{% block title %}New Schedule{% endblock %}
{% block form %}
    <div class="col-md-12">
        <form id="schedule_form" class="form-horizontal" method="POST" action="{% url 'schedule' %}">
            {% csrf_token %}
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_start">start</label>
                    <input hidden id="id_start" name="start">
                    <div class='input-group date' id='datetimepicker1'>
                        <input type='text' id="id_start_dp" class="form-control" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <div class="text-danger">
                        {{ form.start.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_duration">duration</label>
                    <div class="row">
                        <input hidden id="id_duration" name="duration">
                        <div class="col-md-5">
                            <div class='input-group'>
                                <input type='number' id="id_duration_hour" min="0" max="6" class="form-control" value="0"/>
                                <span class="input-group-addon">
                                    <span>hours</span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1">
                            <div class='input-group'>
                                <input type='number' id="id_duration_minute" min="0" max="59" class="form-control" value="30"/>
                                <span class="input-group-addon">
                                    <span>minutes</span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="text-danger">
                        {{ form.duration.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <button id="id_save_button" class="btn btn-primary" type="button" onclick="cleanData()"><span class="glyphicon glyphicon-save"> save</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block sidebar_image %}{% static 'base/img/schedule.png' %}{% endblock %}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
        function cleanTwoDigitInteger(number) {
            return Math.floor(number / 10) + '' + number % 10;
        }
        function cleanData() {
            let start = $('#id_start_dp').val();
            start = new Date(start);
            start = `${start.getFullYear()}-${cleanTwoDigitInteger(start.getMonth()+1)}-${cleanTwoDigitInteger(start.getDate())}T${cleanTwoDigitInteger(start.getHours())}:${cleanTwoDigitInteger(start.getMinutes())}:${cleanTwoDigitInteger(start.getSeconds())}`;
            let duration = parseInt($('#id_duration_hour').val() * 60) + parseInt($('#id_duration_minute').val());
            $('#id_start').val(start);
            $('#id_duration').val(duration);
            $('#schedule_form').submit()
        }
    </script>
{% endblock %}

Project/barber/templates/barber/new_service.html
{% extends 'base/base_form.html' %}
{% load static %}
{% block title %}New Service{% endblock %}
{% block form %}
    <div class="col-md-12">
        <form id="service_form" class="form-horizontal" method="POST" action="{% url 'add_service' %}">
            {% csrf_token %}
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_service_name">Service Name</label>
                    <input type='text' id="id_service_name" class="form-control" name="service_name" />
                    <div class="text-danger">
                        {{ form.service_name.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_duration">Duration</label>
                    <div class="row">
                        <input hidden id="id_duration" name="duration">
                        <div class="col-md-5">
                            <div class='input-group'>
                                <input type='number' id="id_duration_hour" min="0" max="6" class="form-control" value="0"/>
                                <span class="input-group-addon">
                                    <span>hours</span>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1">
                            <div class='input-group'>
                                <input type='number' id="id_duration_minute" min="0" max="59" class="form-control" value="30"/>
                                <span class="input-group-addon">
                                    <span>minutes</span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="text-danger">
                        {{ form.duration.errors }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_price">Price</label>
                    <input type='text' id="id_price" class="form-control" name="price"/>
                    <div class="text-danger">
                        {{ form.price.errors }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_discounted_price">Discounted Price</label>
                    <input type='text' id="id_discounted_price" class="form-control" name="discounted_price"/>
                    <div class="text-danger">
                        {{ form.discounted_price.errors }}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">
                    <button id="id_save_button" class="btn btn-primary" type="button" onclick="cleanData()"><span class="glyphicon glyphicon-save"> add </span></button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block sidebar_image %}{% static 'base/img/new_service.png' %}{% endblock %}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
        function cleanData() {
            let duration = parseInt($('#id_duration_hour').val() * 60) + parseInt($('#id_duration_minute').val());
            $('#id_duration').val(duration);
            $('#service_form').submit();
        }
    </script>
{% endblock %}

Project/barber/templates/barber/schedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BeCute Customer</title>
</head>
<body>
{% block content %}

your schedule from {{start_time}} to {{end_time}}:<br>
{% for schedule in schedules %}
    no. {{schedule.id}} at {{schedule.start}} for {{schedule.duration}}<br>
{% endfor %}
<br>
reserved times from {{start_time}} to {{end_time}}:<br>
{% for reserve in reservations %}
no. {{reserve.id}} at {{reserve.start}} for {{reserve.duration}}<br>
{% endfor %}
<br>
<br>
<form method="post">
add new free time:
{% csrf_token %}
    <input type="hidden" name="type" value="add">
    enter year : <input type="text" name="year"><br>
    enter month : <input type="text" name="month"><br>
    enter day : <input type="text" name="day"><br>
    enter hour : <input type="text" name="hour"><br>
    enter minute : <input type="text" name="minute"><br>
    enter duration(minute) : <input type="text" name="duration"><br>
    <input type="submit" value="add">
</form>
<br>
<form method="post">
    remove free time:
    {% csrf_token %}
    <input type="hidden" name="type" value="remove">
    enter free time no. : <input type="text" name="free_time"><br>
    <input type="submit" value="remove">
</form>

{% endblock %}
</body>
</html>