Project/BeCute/urls.py
from django.contrib import admin
from django.urls import path, include

from BeCute.views import logout_view, index_view, error_view
from django.contrib.auth.decorators import login_required
from haystack.views import basic_search
from . import views

urlpatterns = [
    path('', index_view, name='index'),
    path("admin/", admin.site.urls),
    path("customers/", include("customer.urls")),
    path("barbers/", include("barber.urls")),
    path("accounts/", include("account.urls")),
    path(r'logout/', logout_view, name='logout'),
    path(r'search/', login_required(basic_search), name='basic_search'),
    path("error/", error_view, name="error")
]

Project/customer/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    path("", views.main),
    # path("search/", login_required(views.search)),
    path(
        "profile/",
        login_required(views.CustomerProfileView.as_view()),
        name="customer-profile",
    ),
    path("reserve/", login_required(views.reserve), name="reserve"),
    path("cancel/<int:reserve_id>/", login_required(views.cancel), name="cancel"),
    path(
        "<str:barbershop_name>/comment/",
        login_required(views.CreateComment.as_view()),
        name="comment",
    ),
    path("<str:customer_username>/profile",
        views.profile,
         name='customer_info'),
    path("ajax/load-services/", views.load_services, name="ajax_load_services"),
    path("ajax/load-services-list/", views.load_services_list, name="ajax_load_services_list"),
    path("ajax/explore-all/", views.explore_all, name="ajax_explore_all"),
    path("ajax/explore-discount-givers/", views.explore_discount_givers, name="ajax_explore_discount_givers"),
    path("explore/", login_required(views.explore), name="explore")
]

Project/customer/models.py
from django.db import models

from account.models import CustomUser
from barber.models import BarberShop, Service


class Reservation(models.Model):
    STATE_RESERVED = "R"
    STATE_DONE = "D"
    STATE_CANCELED = "C"
    STATES = (
        (STATE_RESERVED, "reserved"),
        (STATE_DONE, "done"),
        (STATE_CANCELED, "canceled"),
    )

    shop = models.ForeignKey(BarberShop, on_delete=models.CASCADE, default=1234567)
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=1234567)
    start = models.DateTimeField()
    duration = models.DurationField()
    service = models.ForeignKey(Service, on_delete=models.CASCADE, default='')
    state = models.CharField(max_length=1, choices=STATES)


class Comment(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    barbershop = models.ForeignKey(BarberShop, on_delete=models.CASCADE)
    rate = models.IntegerField(default=0, name='rate')
    content = models.CharField(max_length=1000, default='Nice!')

Project/customer/forms.py
from django import forms

from customer.models import Comment


class CommentForm(forms.ModelForm):
    rate = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = Comment
        fields = ['content', 'rate']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        self.barbershop = kwargs.pop("barbershop")
        super().__init__(*args, **kwargs)

    def save(self, **kwargs):
        data = self.cleaned_data
        rate = data.pop("rate")
        content = data.pop("content")
        user = self.request.user
        barbershop = self.barbershop
        comment_created = Comment(rate=rate, customer=user, content=content, barbershop=barbershop)
        comment_created.save()
        return comment_created

Project/customer/views.py
import datetime

from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView, CreateView

from BeCute.misc import parse_datetime
from account.models import CustomUser
from barber.models import Schedule, BarberShop, Service, BarberService
from customer.forms import CommentForm
from customer.models import Reservation, Comment


# from django.views.generic.edit import CreateView


def main(request):
    print("customer index")
    request.session['user_type'] = 'customer'
    request.session['page'] = 'profile'
    return render(request, "customer/index.html", context={})


class CreateComment(CreateView):
    template_name = "customer/comment.html"
    form_class = CommentForm

    def get_success_url(self):
        return reverse('barber_info', kwargs={'barbershop_id': self.barbershop_name})

    def dispatch(self, request, *args, **kwargs):
        self.barbershop_name = kwargs['barbershop_name']
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CreateComment, self).get_form_kwargs()
        barber_shop = BarberShop.objects.get(name=self.barbershop_name)
        kwargs.update({'request': self.request, 'barbershop': barber_shop})
        return kwargs


def reserve(request):
    request.session['user_type'] = 'customer'
    request.session['page'] = 'reserve'
    if request.method == "POST":
        start = parse_datetime(request.POST.get("start", ""))
        try:
            shop = BarberShop.objects.get(id=int(request.POST.get("shop_id")))
            service_name = str(request.POST.get("id_service"))
            service = shop.service.get(id=service_name)
            duration = service.duration
        except (TypeError, ValueError, BarberShop.DoesNotExist):
            shop = None
            duration = None
        if not (start and duration and shop):
            # return HttpResponse("bad request NONE")
            request.session['user_type'] = 'customer'
            request.session['error_message'] = 'Bad Request!'
            return redirect("/error/")

        if (
            Reservation.objects.filter(
                shop=shop, start__lt=start + duration, start__gte=start - F("duration")
            ).exists()
            or not Schedule.objects.filter(
            shop=shop, start__lte=start, start__gte=start + duration - F("duration")
        ).exists()
        ):
            # return HttpResponse("requested time is not available")
            request.session['user_type'] = 'customer'
            request.session['error_message'] = 'Requested time is not available!'
            return redirect("/error/")

        Reservation.objects.create(
            shop=shop,
            customer=request.user,
            duration=duration,
            start=start,
            state=Reservation.STATE_RESERVED,
            service=service
        )

        return redirect("/customers/profile")

    else:
        shops = BarberShop.objects.values_list("id", "name")
        return render(request, "customer/new_reservation.html", {"shops": shops})


def cancel(request, reserve_id):
    request.session['user_type'] = 'customer'
    request.session['page'] = 'cancel'
    Reservation.objects.filter(id=reserve_id, customer=request.user).delete()
    return redirect("/customers/profile")


def search(request):
    # if request.method == 'GET':
    #     body = json.loads(request.body)
    #     point = Point(body["long"], body["latt"])

    # search_result = BarberShop.objects.annotate(
    #     distance=Distance('location', point)
    # ).order_by('distance').all()

    # return HttpResponse(json.dumps(search_result))
    request.session['user_type'] = 'customer'
    request.session['page'] = 'search'
    return HttpResponse(" this is search page of costumer")


class CustomerProfileView(TemplateView):
    template_name = "customer/profile.html"

    def get_context_data(self, **kwargs):
        self.request.session['user_type'] = 'customer'
        self.request.session['page'] = 'profile'
        context = super(CustomerProfileView, self).get_context_data(**kwargs)
        user_reservations = Reservation.objects.filter(customer=self.request.user)
        upcoming_reservations = user_reservations.filter(
            state=Reservation.STATE_RESERVED,
            start__gte=datetime.datetime.now()
        ).order_by("start")[:3]
        previous_reservations = user_reservations.filter(
            start__lt=datetime.datetime.now()
        ).order_by("state", "-start")
        context.update(
            upcoming_reservations=upcoming_reservations,
            previous_reservations=previous_reservations,
        )
        return context


def profile(request, customer_username):
    # if request.session['user_type'] == 'customer':
    #     request.session['user_type'] = 'customer'
    #     request.session['page'] = 'profile'
    request.session['page'] = 'profile_visit'
    customer = CustomUser.objects.get(
        username=customer_username
    )

    return render(request, 'customer/info.html', {'customer': customer})


def load_services(request):
    request.session['user_type'] = 'customer'
    request.session['page'] = 'load_services'
    shop_id = request.GET.get('shop_id')
    barbershop = BarberShop.objects.filter(id=shop_id)
    barbershop = list(set(barbershop))[0]
    services = barbershop.service.all()
    return render(request, 'customer/services_dropdown.html', {'services': services})


def load_services_list(request):
    request.session['user_type'] = 'customer'
    request.session['page'] = 'load_services_list'
    shop_id = request.GET.get('shop_id')
    barbershop = BarberShop.objects.filter(id=shop_id)
    barbershop = list(set(barbershop))[0]
    services = barbershop.service.all()
    return render(request, 'customer/services_table.html', {'services': services})


class RatingAndObject():
    def __init__(self, object, rating):
        self.barbershop = object
        self.rating = rating
        self.int_rating = int(rating)


class RatingAndObjectAndServices():
    def __init__(self, object, rating, services):
        self.barbershop = object
        self.rating = rating
        self.int_rating = int(rating)
        self.discounted_services = services


def explore(request):
    request.session['user_type'] = 'customer'
    request.session['page'] = 'search'
    return render(request, 'customer/explore.html')


def explore_all(request):
    request.session['user_type'] = 'customer'
    request.session['page'] = 'search'
    all_barbershops = list(BarberShop.objects.all())
    list_of_barbershops = []
    for barbershop in all_barbershops:
        my_comments_list = list(Comment.objects.filter(barbershop=barbershop))
        rating = 0
        for comment in my_comments_list:
            rating += comment.rate
        if len(my_comments_list) != 0:
            rating /= len(my_comments_list)
        else:
            rating = 0
        list_of_barbershops.append(RatingAndObject(barbershop, rating))
    list_of_barbershops.sort(key=lambda x: x.rating, reverse=True)
    return render(request, 'customer/explore_all_table.html', {'list_of_barbershops': list_of_barbershops})


def explore_discount_givers(request):
    request.session['user_type'] = 'customer'
    request.session['page'] = 'search'
    all_barbershops = list(BarberShop.objects.all())
    list_of_barbershops = []
    for barbershop in all_barbershops:
        my_comments_list = list(Comment.objects.filter(barbershop=barbershop))
        rating = 0
        for comment in my_comments_list:
            rating += comment.rate
        if len(my_comments_list) != 0:
            rating /= len(my_comments_list)
        else:
            rating = 0
        list_of_barbershops.append(RatingAndObject(barbershop, rating))
    list_of_barbershops.sort(key=lambda x: x.rating, reverse=True)
    list_of_discounted_barbershops = []
    for barbershop_obj in list_of_barbershops:
        flag = False
        services = []
        services_barbershop = list(BarberService.objects.filter(shop=barbershop_obj.barbershop))
        services_barbershop2 = []
        for s in services_barbershop:
            services_barbershop2.append(s.service)
        for service in services_barbershop2:
            if service.discounted_price != 0:
                services.append(service)
                flag = True
        if flag:
            list_of_discounted_barbershops.append(RatingAndObjectAndServices(barbershop_obj.barbershop, barbershop_obj.rating, services))
    # print(list_of_discounted_barbershops[0].rating)
    return render(request, 'customer/explore_discount_table.html', {'list_of_discounted_barbershops': list_of_discounted_barbershops})

Project/customer/templates/customer/cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BeCute Customer</title>
</head>
<body>
{% block content %}
current reservations:<br>
{% for reserve in reserves %}
    no. {{reserve.id}} at {{reserve.start}} for {{reserve.duration}} in {{reserve.shop.name}} store<br>
{% endfor %}
<br>
<br>

cancel a reservation:
<form method="post">
    {% csrf_token %}
    reservation no. : <input type="text" name="reserve_id"><br>
    <input type="submit" value="cancel">
</form>

{% endblock %}
</body>
</html>

Project/customer/templates/customer/comment.html
{% extends "base/base.html" %}
{% block styles %}{% endblock %}
{% block title %}signup{% endblock %}

{% block content %}
    {% load static %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-xs-12 center-horizontal-vertical">
                <form id="comment_form" class="form-horizontal" method="POST" style="margin-top: 12px">
                    {% csrf_token %}
                    {#                    <div class="form-group">#}
                    {#                        <img src="{% static 'base/img/logo.jpeg' %}" class="text-center center-block"#}
                    {#                             width="100px" height="100px">#}
                    {#                        <h2 class="text-center logo-text">‌BeCute!</h2>#}
                    {#                    </div>#}
                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-1">
                            <input type="text" id="id_content" name="content" placeholder="Content"
                                   class="form-control">
                            <div class="text-danger">
                                {{ form.content.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-1">
                            <input type="text" id="id_rate" name="rate" placeholder="Rate 1-5" class="form-control">
                            <div class="text-danger">
                                {{ form.rate.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-1">
                            <button id="id_submit_button" class="btn btn-primary center-block btn-block" type="submit">
                                Submit
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Project/customer/templates/customer/explore.html
{% extends 'base/base_form.html' %}
{% load static %}
{% block title %}Explore{% endblock %}
{% block form %}
    <div class="col-md-12">
        <form id="schedule_form" class="form-horizontal" data-all-url="{% url 'ajax_explore_all' %}" data-discount-givers-url="{% url 'ajax_explore_discount_givers' %}" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_options_id">Select Explore Option</label>
                    <select id="id_options_id" class="form-control">
                        <option value="" selected> </option>
                        <option value="1">All Barbershops</option>
                        <option value="2">Discounted Barbershops</option>
                    </select>
{#                    <div class="text-danger">#}
{#                        {{ form.shop.errors }}#}
{#                    </div>#}
                </div>
            </div>

{#            <div class="form-group">#}
{##}
{#            <div id="id_shop_id" class="col-md-10">#}
                    {#                    <div id="id_shop_list" class="table-responsive">#}
                    {##}
                    {#                    </div>#}
{#                <label for="id_shop_list">Barbershops</label>#}
{#                <select id="id_shop_list" name="id_service" class="form-control">#}
{##}
{#                </select>#}
{#                <div class="text-danger">#}
{#                        {{ form.service.errors }}#}
{#                </div>#}
{#            </div>#}
            <div class="form-group">
                <div class="col-md-10">
{#                    <label for="id_shop_list">Barbershops</label>#}
                    <div id="id_shop_list" class="table-responsive">

                    </div>
                    <div class="text-danger">
                        {{ form.service.errors }}
                    </div>
                </div>
            </div>
{#            <div class="form-group">#}
{#                <div class="col-md-10">#}
{#                    <label for="id_service_id">Choose Your Service</label>#}
{#                    <select id="id_service_option" name="id_service" class="form-control">#}
{#                        <div id="id_service_option"></div>#}
{#                    </select>#}
{##}
{#                    <div class="text-danger">#}
{#                        {{ form.service.errors }}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <div class="col-md-10">#}
{#                    <label for="id_start">start</label>#}
{#                    <input hidden id="id_start" name="start">#}
{#                    <div class='input-group date' id='datetimepicker1'>#}
{#                        <input type='text' id="id_start_dp" class="form-control" />#}
{#                        <span class="input-group-addon">#}
{#                            <span class="glyphicon glyphicon-calendar"></span>#}
{#                        </span>#}
{#                    </div>#}
{#                    <div class="text-danger">#}
{#                        {{ form.start.errors }}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <div class="col-md-3">#}
{#                    <button id="id_reserve_button" class="btn btn-success" type="button" onclick="cleanData()"><span class="glyphicon glyphicon-check"></span> reserve</button>#}
{#                </div>#}
{#            </div>#}
        </form>
    </div>
{% endblock %}
{% block sidebar_image %}{% static 'base/img/explore.png' %}{% endblock %}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
        function cleanTwoDigitInteger(number) {
            return Math.floor(number / 10) + '' + number % 10;
        }
        function cleanData() {
            {#let start = $('#id_start_dp').val();#}
            {#start = new Date(start);#}
            {#start = `${start.getFullYear()}-${cleanTwoDigitInteger(start.getMonth()+1)}-${cleanTwoDigitInteger(start.getDate())}T${cleanTwoDigitInteger(start.getHours())}:${cleanTwoDigitInteger(start.getMinutes())}:${cleanTwoDigitInteger(start.getSeconds())}`;#}
            {#let duration = parseInt($('#id_duration_hour').val() * 60) + parseInt($('#id_duration_minute').val());#}
            {#$('#id_start').val(start);#}
            {#$('#id_duration').val(duration);#}
            $('#schedule_form').submit();
        }
        $('#id_options_id').change(function () {
            var choice = document.getElementById("id_options_id").value;
            if ($(this).val() == "1") {
                var url1 = $('#schedule_form').attr("data-all-url");

                $.ajax({
                    url: url1,
                    data: {
                    },
                    success: function(data) {
                        $('#id_shop_list').html(data);
                    }
                });
            } else {
                var url2 = $('#schedule_form').attr("data-discount-givers-url");

                $.ajax({
                    url: url2,
                    data: {
                    },
                    success: function(data) {
                        $('#id_shop_list').html(data);
                    }
                });
            }

        });
    </script>
{% endblock %}

Project/customer/templates/customer/explore_all_table.html
<h3>Barbershops</h3>
{% if list_of_barbershops %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Name</th>
                <th>Rating</th>
            </tr>
            {% for shop in list_of_barbershops %}
                <tr>
                    <td><a href='{% url 'barber_info' shop.barbershop.name %}'
                                       class="badge badge-primary">{{ shop.barbershop.name }}</a></td>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
                            <style>
                                .checked {
                                    color: orange;
                                }
                            </style>
                    <td>
                                {% if shop.int_rating == 0%}
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                {% elif shop.int_rating == 1 %}
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                {% elif shop.int_rating == 2 %}
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                {% elif shop.int_rating == 3 %}
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                {% elif shop.int_rating == 4 %}
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                {% elif shop.int_rating == 5 %}
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                {% endif %}
                        <p style="color: orangered; display: inline" > {{ shop.rating }} </p>
                            </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% else %}
    <div class="text-info">No barbershop yet.</div>
{% endif %}

Project/customer/templates/customer/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BeCute Customer</title>
</head>
<body>
Customer landing page
</body>
</html>

Project/customer/templates/customer/new_reservation.html
{% extends 'base/base_form.html' %}
{% load static %}
{% block title %}New Reservation{% endblock %}
{% block form %}
    <div class="col-md-12">
        <form id="schedule_form" class="form-horizontal" method="POST" action="{% url 'reserve' %}" data-services-url="{% url 'ajax_load_services' %}" data-services-list-url="{% url 'ajax_load_services_list' %}" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_shop_id">Shop</label>
                    <select id="id_shop_id" name="shop_id" class="form-control">
                        <option value="" selected> </option>
                        {% for shop_id, shop_name in shops %}
                            <option value="{{ shop_id }}">{{ shop_name }}</option>
                        {% endfor %}
                    </select>
                    <div class="text-danger">
                        {{ form.shop.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <div id="id_service_list" class="table-responsive">

                    </div>
                    <div class="text-danger">
                        {{ form.service.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_service_id">Choose Your Service</label>
                    <select id="id_service_option" name="id_service" class="form-control">
{#                        <div id="id_service_option"></div>#}
                    </select>

                    <div class="text-danger">
                        {{ form.service.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label for="id_start">start</label>
                    <input hidden id="id_start" name="start">
                    <div class='input-group date' id='datetimepicker1'>
                        <input type='text' id="id_start_dp" class="form-control" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <div class="text-danger">
                        {{ form.start.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <button id="id_reserve_button" class="btn btn-success" type="button" onclick="cleanData()"><span class="glyphicon glyphicon-check"></span> reserve</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block sidebar_image %}{% static 'base/img/schedule.png' %}{% endblock %}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
        function cleanTwoDigitInteger(number) {
            return Math.floor(number / 10) + '' + number % 10;
        }
        function cleanData() {
            let start = $('#id_start_dp').val();
            start = new Date(start);
            start = `${start.getFullYear()}-${cleanTwoDigitInteger(start.getMonth()+1)}-${cleanTwoDigitInteger(start.getDate())}T${cleanTwoDigitInteger(start.getHours())}:${cleanTwoDigitInteger(start.getMinutes())}:${cleanTwoDigitInteger(start.getSeconds())}`;
            {#let duration = parseInt($('#id_duration_hour').val() * 60) + parseInt($('#id_duration_minute').val());#}
            $('#id_start').val(start);
            {#$('#id_duration').val(duration);#}
            $('#schedule_form').submit();
        }
        $('#id_shop_id').change(function () {
            var url = $('#schedule_form').attr("data-services-url");
            var shopID = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'shop_id': shopID
                },
                success: function(data) {
                    $('#id_service_option').html(data);
                }
            });

            var url2 = $('#schedule_form').attr("data-services-list-url");

            $.ajax({
                url: url2,
                data: {
                    'shop_id': shopID
                },
                success: function(data) {
                    $('#id_service_list').html(data);
                }
            });

        });
    </script>
{% endblock %}

Project/customer/templates/customer/reserve.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BeCute Customer</title>
</head>
<body>
{% block content %}

free times at {{shop.name}} barbershop:<br>
{% for schedule in schedules %}
    at {{schedule.start}} for {{schedule.duration}}<br>
{% endfor %}

<br>
current reservations:<br>
{% for reserve in reserves %}
    at {{reserve.start}} for {{reserve.duration}}<br>
{% endfor %}
<br>
<br>

<form action="/customer/reserve/{{shop.id}}/" method="post">
reserve a time:
{% csrf_token %}
    enter year : <input type="text" name="year"><br>
    enter month : <input type="text" name="month"><br>
    enter day : <input type="text" name="day"><br>
    enter hour : <input type="text" name="hour"><br>
    enter minute : <input type="text" name="minute"><br>
    enter duration(minute) : <input type="text" name="duration"><br>
    <input type="submit" value="reserve">
</form>

{% endblock %}
</body>
</html>

Project/customer/templates/customer/services_dropdown.html
{#{{ services.count }}#}
{% for service in services %}
    <option value="{{ service.pk }}"> {{ service.name }} </option>
{% endfor %}